export default () => ({
  bot_id: 0,
  assistant_id: '',
  domain: '',
  sku: '',
  name: '',
  categories: [],
  description: '',
  price: 0,
  offer_price: 0,
  currency: '',
  image_url: '',
  product_url: '',
  product_id: '',
  available: true,
  stock: 0,
  options: [],
  variants: [],
  reviews: [],
  general_rating: 0,
  original_object: {},
  intent: '',
  examples: '',
});
